# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

#EVENTS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


#Jobs
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
    - uses: actions/checkout@v3

  #Configuring JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

  #Setting up the gradle permission
    - name: Setting permission
    - run: chmod +x gradlew

  #Running gradle build
    - name: build
    - run: ./gradlew clean build
